version: '3.8'

services:
  postgres:
    container_name: dockerized_postgress
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-boot-app:
    container_name: dockerized_spring
    build:
      dockerfile: dockerfile.java
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microservices_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  node-app:
    container_name: dockerized_node
    build: 
      dockerfile: dockerfile.node
    ports:
      - "8081:8081"

volumes:
  pgdata: